BoxLayout:
    orientation: "vertical"
    BoxLayout:
        TextInput:
            id: user_input
            multiline: False
            text: ""
            on_text: app.handle_update()
        BoxLayout:
            orientation: "vertical"
            size_hint_x: 0.2
            Button:
                text: "Up"
                on_press: app.handle_increment(user_input.text, 1)
            Button:
                text: "Down"
                on_press: app.handle_increment(user_input.text, -1)
#    Button:
#        text: "Convert miles to km"
    Label:
        text: app.km_output
        color: (1, 1, 0, 1)